#cloud-config
# Based on https://www.molnar-peter.hu/en/ubuntu-jammy-netinstall-pxe.html
autoinstall:
  identity:
    hostname: jammy-desktop-crypt
    # The following credentials have no effect - the user will be set up by gnome-initial-setup
    password: $6$5lpwCLsKLEzMkSJc$keOAhA6aO/5RocGThmhVA7LSNuW911Rx5HHXFEa75oGK20cEdAAgn14H5f5nGeq6QgcSyLPrWcg1.JvjXbhrN/
    realname: Ubuntu user
    username: ubuntu
  # Let NetworkManager manage all devices on this system
  network:
    version: 2
    renderer: NetworkManager
  refresh-installer:
    update: no
  keyboard:
    layout: gb
    toggle: null
    variant: ''
  locale: en_GB.UTF-8
  storage:
    config:
    - { ptable: gpt, size: largest, wipe: superblock, preserve: false, name: '', grub_device: false, type: disk, id: disk-vda }
    - { device: disk-vda, size: 50M, wipe: superblock, flag: boot, number: 1, preserve: false, grub_device: true, type: partition, id: partition-efi }
    - { fstype: fat32, volume: partition-efi, preserve: false, type: format, id: format-efi }
    - { device: disk-vda, size: 10G, wipe: superblock, flag: '', number: 2, preserve: false, grub_device: false, type: partition, id: partition-boot }
    - { fstype: ext4, volume: partition-boot, preserve: false, type: format, id: format-boot }
    - { device: disk-vda, size: -1, wipe: superblock, flag: '', number: 3, preserve: false, grub_device: false, type: partition, id: partition-root }
    # DM crypt - unlike the credentials above, this key does get used:
    - { volume: partition-root, key: 'ubuntu', preserve: false, type: dm_crypt, id: dm_crypt-0 }
    - { name: ubuntu-vg, devices: [ dm_crypt-0 ], preserve: false, type: lvm_volgroup, id: lvm_volgroup-0 }
    - { name: ubuntu-lv, volgroup: lvm_volgroup-0, size: -1, wipe: superblock, preserve: false, type: lvm_partition, id: lvm_partition-0 }
    - { fstype: ext4, volume: lvm_partition-0, preserve: false, type: format, id: format-root }
    - { path: /, device: format-root, type: mount, id: mount-2 }
    - { path: /boot, device: format-boot, type: mount, id: mount-1 }
    - { path: /boot/efi, device: format-efi, type: mount, id: mount-0 }
    swap:
      swap: 1G
    grub:
      # This avoids a loop where we autoinstall, reboot to the autoinstaller USB, then autoinstall again and so on.
      reorder_uefi: False
  # From https://askubuntu.com/a/1410679 - for repeatability whether install is online or offline.
  #updates: security
  #apt:
  #  disable_suites: [security]
  early-commands:
  - mount > /mount-early.txt
  - /cdrom/attempt-wifi-connection.sh
  - echo "Choose system hostname" > /dev/console
  - play /cdrom/drip.ogg
  #- bash -c 'read </dev/console; echo "You entered $REPLY"'
  late-commands:
  - if [ -z "$(dig +short gb.archive.ubuntu.com)" ]; then echo OFFLINE; else echo ONLINE; fi
  - mkdir /target/cdrom
  - mount --bind /cdrom /target/cdrom
  - curtin in-target --target=/target -- sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/' /etc/default/grub
  - curtin in-target --target=/target -- update-grub
  - curtin in-target --target=/target -- /cdrom/setup-secureboot-mok.sh
  - bash -c 'cp /etc/NetworkManager/system-connections/*.nmconnection /target/etc/NetworkManager/system-connections/ || true'
  - umount /target/cdrom
  - rm -r /target/cdrom
  - mv /target/etc/apt/sources.list.curtin.old /target/etc/apt/sources.list
  - mount > /target/mount-late.txt
  - mv /mount-early.txt /target/
  - tpm2_pcrread > /target/late-tpm2_pcrread.txt || true
  - tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements > /target/late-tpm2_eventlog.txt || true
  version: 1
  #- mount --bind /cdrom /target/cdrom